### ISSUE TITLE
[Bug] Flatpak version fails to write the High Score table

### ISSUE THREAD

**Issue by chang-zhao** [flathub/net.sourceforge.lgames.LBreakoutHD#1]
Flatpak version fails to write the high score table. Terminal output:

```
Loading hiscores /app/var/lbreakouthd.hscr
...blah blah blah...
ERROR: hiscores.cpp:133: save(): Could not open hiscores file /app/var/lbreakouthd.hscr
```

So every run the table is initialized as if I never played before.

The dev says in https://sourceforge.net/p/lgames/bugs/93/

> That is a bug with the flatpak package, you will need to report this to the respective maintainer (which is not me). The file lbreakouthd.hscr must be created with permission 666. This seems to be missing in the flatpak package.
>
> As a workaround you can start a console and run
> sudo touch /app/var/lbreakouthd.hscr
> sudo chmod 666 /app/var/lbreakouthd.hscr
> That should do the trick.

**Comment by nbenitez** [comment]
Fixed along with latest version published on flathub. Thanks.
